name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout external repository
        uses: actions/checkout@v2
        with:
          repository: revoltpublishing/rev-infra
          path: rev-infra
      # Step 2: Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 3: Set up Kubectl
      - name: Set up kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}"
          kubectl config get-contexts

      # Step 4: Deploy to Kubernetes
      - name: Deploy to EKS
        run: |
          echo ls
          aws eks update-kubeconfig --name {{secrets.REV_CLUSTER}} --region {{secrets.REV_CLUSTER_REGION}}
          kubectl apply -f rev-infra/backend/revolt/k8/deployment.yml
          kubectl apply -f rev-infra/backend/revolt/k8/service.yml

      # Optional: Notify deployment success or failure
      - name: Notify
        if: success()
        run: echo "Deployment succeeded!"
