name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout external repository
        uses: actions/checkout@v2
        with:
          repository: revoltpublishing/rev-infra
          path: rev-infra
      # Step 2: Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
          IMAGE_TAG: "backend_main_latest_tag"
        run: |
          echo $ECR_REGISTRY
          echo $ECR_REPOSITORY
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "image_tag=$IMAGE_TAG" 
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      # Step 3: Set up Kubectl
      - name: Set up kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}"
          kubectl config get-contexts

      # Step 4: Deploy to Kubernetes
      - name: Deploy to EKS
        run: |
          ls
          aws eks update-kubeconfig --name revolt-publishing-cluster --region ap-south-1
          helm install rev-infra/backend/revolt/helm
      # Optional: Notify deployment success or failure
      - name: Notify
        if: success()
        run: echo "Deployment succeeded!"
